services:
  fastapi-app:    
    build: 
      context: .      
      dockerfile: Dockerfile      
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://${DATABASE_USER}:${DATABASE_PASSWORD}@db:5432/${DATABASE_NAME}
      - PYTHONPATH=/app/src
    depends_on:
      - db
    networks:
      - app-network
    volumes:
      - .:/app
    env_file:
      - .env

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_NAME=${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    env_file:
      - .env

  
networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
