"""modify_cats

Revision ID: 444df6cef765
Revises: 641a9341f720
Create Date: 2025-10-03 20:14:51.863832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '444df6cef765'
down_revision: Union[str, Sequence[str], None] = '641a9341f720'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cats', sa.Column('password', sa.String(length=255), nullable=False))
    op.add_column('cats', sa.Column('refresh_token', sa.String(length=255), nullable=True))
    op.add_column('cats', sa.Column('reset_token', sa.String(length=255), nullable=True))
    op.add_column('cats', sa.Column('is_staff', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cats', 'is_staff')
    op.drop_column('cats', 'reset_token')
    op.drop_column('cats', 'refresh_token')
    op.drop_column('cats', 'password')
    # ### end Alembic commands ###
