"""init

Revision ID: 56fbbbb98b0b
Revises: 
Create Date: 2025-10-24 15:09:17.664639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56fbbbb98b0b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cats',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('refresh_token', sa.String(length=255), nullable=True),
    sa.Column('reset_token', sa.String(length=255), nullable=True),
    sa.Column('years_of_experience', sa.Integer(), nullable=False),
    sa.Column('breed', sa.String(length=50), nullable=False),
    sa.Column('salary', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_staff', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('missions',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('mission_cats',
    sa.Column('mission_uuid', sa.UUID(), nullable=False),
    sa.Column('cat_uuid', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['cat_uuid'], ['cats.uuid'], ),
    sa.ForeignKeyConstraint(['mission_uuid'], ['missions.uuid'], ),
    sa.PrimaryKeyConstraint('mission_uuid', 'cat_uuid')
    )
    op.create_table('targets',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('mission_uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mission_uuid'], ['missions.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('notes',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('content', sa.String(length=255), nullable=False),
    sa.Column('cat_uuid', sa.UUID(), nullable=False),
    sa.Column('target_uuid', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cat_uuid'], ['cats.uuid'], ),
    sa.ForeignKeyConstraint(['target_uuid'], ['targets.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notes')
    op.drop_table('targets')
    op.drop_table('mission_cats')
    op.drop_table('missions')
    op.drop_table('cats')
    # ### end Alembic commands ###
