"""add relationship targets_cats

Revision ID: e97049c88a47
Revises: 56fbbbb98b0b
Create Date: 2025-10-25 17:01:11.384022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e97049c88a47'
down_revision: Union[str, Sequence[str], None] = '56fbbbb98b0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('targets_cats',
    sa.Column('target_uuid', sa.UUID(), nullable=False),
    sa.Column('cat_uuid', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['cat_uuid'], ['cats.uuid'], ),
    sa.ForeignKeyConstraint(['target_uuid'], ['targets.uuid'], ),
    sa.PrimaryKeyConstraint('target_uuid', 'cat_uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('targets_cats')
    # ### end Alembic commands ###
